#!/bin/sh

wget -qO $CADDYIndexPage -o /usr/share/caddy/index.html && unzip -qo /usr/share/caddy/index.html -d /usr/share/caddy/ && mv /usr/share/caddy/*/* /usr/share/caddy/

exec 2>&1
exec caddy run --config /workdir/Caddyfile --adapter caddyfile
